-- Bokmal core schema.
--
-- Conventions:
--   * All primary keys are GUIDs, generated by the application (UUID v7 at runtime,
--     literal values in seed scripts). Nothing is generated by the database, so an
--     entity is fully valid the moment it is constructed and whole object graphs can
--     be written in a single transaction.
--   * Columns are declared with the type names 'uuid' and 'datetime' rather than the plain
--     TEXT that SQLite actually stores them as. SQLite is dynamically typed and ignores the
--     difference, but the entity generator reads these names to recover the CLR types --
--     declared as TEXT it would hand us a string property for every key and every
--     timestamp. The declared type is the only thing carrying that intent, so it is
--     load-bearing, not decoration.
--   * Timestamps are 'datetime' and always UTC, deliberately not 'datetimeoffset'. EF Core
--     refuses to translate ORDER BY over a DateTimeOffset on SQLite at all -- the stored
--     text carries an offset and sorting it lexicographically would be wrong across
--     offsets -- so "my loans, newest first" simply throws. Since every timestamp here is
--     UTC, the offset was carrying no information, and a UTC DateTime sorts identically on
--     every engine. The application pins the kind to UTC on the way in and out; see
--     BokmalDbContextOverrides.

CREATE TABLE borrower (
    id           uuid           NOT NULL PRIMARY KEY,
    email        TEXT           NOT NULL,
    display_name TEXT           NOT NULL,
    joined_at    datetime       NOT NULL
);

-- Email is the stand-in for a real identity, so it has to be unique.
CREATE UNIQUE INDEX ux_borrower_email ON borrower (email);

CREATE TABLE book (
    id             uuid    NOT NULL PRIMARY KEY,
    slug           TEXT    NOT NULL,
    title          TEXT    NOT NULL,
    author         TEXT    NOT NULL,
    genre          TEXT    NOT NULL,
    published_year INTEGER NOT NULL,
    page_count     INTEGER NOT NULL,
    description    TEXT    NOT NULL
);

-- The catalog is addressed by slug in both the API and the UI, so it must be unique.
CREATE UNIQUE INDEX ux_book_slug ON book (slug);

-- A physical copy on a shelf. Availability is tracked here because this is the row the
-- borrow flow compare-and-swaps against.
CREATE TABLE book_copy (
    id          uuid    NOT NULL PRIMARY KEY,
    book_id     uuid    NOT NULL REFERENCES book (id),
    copy_number INTEGER NOT NULL,
    status      TEXT    NOT NULL,
    CONSTRAINT ck_book_copy_status CHECK (status IN ('Available', 'OnLoan'))
);

CREATE INDEX ix_book_copy_book_id ON book_copy (book_id);
CREATE UNIQUE INDEX ux_book_copy_book_id_copy_number ON book_copy (book_id, copy_number);

CREATE TABLE loan (
    id           uuid           NOT NULL PRIMARY KEY,
    book_copy_id uuid           NOT NULL REFERENCES book_copy (id),
    borrower_id  uuid           NOT NULL REFERENCES borrower (id),
    borrowed_at  datetime       NOT NULL,
    due_at       datetime       NOT NULL,
    returned_at  datetime       NULL
);

-- The one invariant the application is never allowed to break: a copy can have at most
-- one loan that has not been returned. Returned loans fall out of the index entirely, so
-- history is unlimited.
--
-- The borrow flow does not depend on this index -- it does its own compare-and-swap on
-- book_copy.status -- so if this constraint ever fires it means there is a bug, and it
-- should surface as one rather than be caught and dressed up as a conflict.
--
-- Note for whoever regenerates the entities: the generator cannot express a partial
-- index. It reads this as a plain unique constraint on the foreign key and concludes a
-- copy has at most one loan ever, which would quietly break loan history. The relation
-- is corrected in BokmalDbContext.OnModelCreatingPartial and pinned by a test.
CREATE UNIQUE INDEX ux_loan_active_book_copy_id ON loan (book_copy_id)
    WHERE returned_at IS NULL;

CREATE INDEX ix_loan_borrower_id ON loan (borrower_id);
CREATE INDEX ix_loan_book_copy_id ON loan (book_copy_id);
